def start_message():
    return (
        "Bienvenido. Cada chat mantiene su propio contexto, playlists y modos guiados.\n\n"
        "Puedes usar el bot de dos formas:\n"
        "1. Comando completo: /music Danza Kuduro\n"
        "2. Comando vacío en modo guiado: /translate, /wiki, /youtube, /music, /playlist, /wallapop\n\n"
        "Comandos principales:\n"
        "/library - abrir la biblioteca de Jellyfin\n"
        "/video <pelicula> - buscar una película\n"
        "/wiki <tema> - buscar en Wikipedia\n"
        "/img <tema> - buscar imágenes\n"
        "/weather <ciudad> - consultar el tiempo\n"
        "/youtube <busqueda> - buscar y enviar un vídeo\n"
        "/music <cancion> - buscar y enviar audio\n"
        "/wallapop - buscar productos con filtros guiados\n"
        "/translate <destino> | <texto> - traducir texto\n"
        "/playlist - gestionar playlists\n"
        "/helper - ver la guía completa\n\n"
        "Ejemplos:\n"
        "/youtube hall of fame\n"
        "/music Danza Kuduro\n"
        "/wallapop iphone 15\n"
        "/translate en | hola mundo"
    )


def helper_message():
    return (
        "Guía completa del bot:\n\n"
        "Información general:\n"
        "- Cada usuario tiene su propio contexto, playlists y sesiones guiadas.\n"
        "- Muchos comandos se pueden usar vacíos y el bot te irá pidiendo lo necesario.\n"
        "- Si escribes un comando que no existe, el bot te avisará.\n\n"
        "Comandos generales:\n"
        "/start - bienvenida y resumen rápido.\n"
        "/helper - guía completa de comandos y modos de uso.\n\n"
        "Biblioteca Jellyfin:\n"
        "/library - abre la biblioteca.\n"
        "/menu - alias de /library.\n"
        "/catalog - alias de /library.\n"
        "/video <pelicula> - busca y reproduce una película.\n"
        "/video - modo guiado: te pregunta qué película quieres ver.\n\n"
        "Wikipedia y búsqueda informativa:\n"
        "/wiki <tema> - busca en Wikipedia.\n"
        "/wiki - modo guiado: te pregunta qué quieres buscar.\n\n"
        "Imágenes:\n"
        "/img <tema> - busca imágenes.\n"
        "/image <tema> - alias de /img.\n"
        "/img - modo guiado: te pregunta qué imagen quieres buscar.\n\n"
        "Tiempo:\n"
        "/weather <ciudad> - consulta el tiempo.\n"
        "/tiempo <ciudad> - alias de /weather.\n"
        "/weather - modo guiado: te pregunta la ciudad.\n\n"
        "YouTube:\n"
        "/youtube <busqueda> - busca y envía automáticamente el mejor vídeo.\n"
        "/youtube - modo guiado: te pregunta qué vídeo quieres buscar.\n\n"
        "Música:\n"
        "/music <cancion> - busca y envía audio.\n"
        "/music - modo guiado: te pregunta qué canción quieres buscar.\n"
        "/music buscar <consulta> - muestra resultados musicales con botones.\n"
        "/music fav <consulta> - guarda una canción en favoritos.\n"
        "/music favs - muestra tus favoritos.\n"
        "/music recomendar - recomienda música según historial y favoritos.\n"
        "/music - también puede usarse vacío para iniciar la búsqueda guiada.\n\n"
        "Wallapop:\n"
        "/wallapop - inicia una búsqueda guiada.\n"
        "/wallapop <producto> - precarga el producto y luego te pide filtros.\n"
        "- Puedes filtrar por estado, rango de precio, ubicación, radio y orden.\n\n"
        "Traducción:\n"
        "/translate <destino> | <texto> - traduce desde idioma automático.\n"
        "/translate <origen> | <destino> | <texto> - traduce indicando idioma origen.\n"
        "/translate - modo guiado: te pide el texto y luego te deja elegir idioma.\n"
        "- Dentro de /translate también puedes enviar una nota de voz en vez de texto.\n"
        "- Tras traducir, puedes usar el botón de pronunciación para escuchar el resultado.\n\n"
        "Playlists:\n"
        "/playlist - abre el gestor interactivo de playlists.\n"
        "/playlist crear <nombre> - crea una playlist.\n"
        "/playlist listas - lista tus playlists.\n"
        "/playlist add <nombre> | <canción> - añade una canción.\n"
        "/playlist ver <nombre> - muestra la playlist.\n"
        "/playlist play <nombre> - reproduce la primera canción.\n"
        "/playlist remove <nombre> | <posición> - quita una canción.\n"
        "/playlist borrar <nombre> - elimina la playlist.\n"
        "- En modo guiado de /playlist puedes elegir la playlist, añadir, quitar, ver, reproducir o borrar con botones.\n\n"
        "Ejemplos rápidos:\n"
        "/library\n"
        "/video interestellar\n"
        "/wiki chuck norris\n"
        "/img cascadas\n"
        "/weather madrid\n"
        "/youtube waka waka shakira\n"
        "/music Danza Kuduro\n"
        "/wallapop steam deck\n"
        "/translate en | hola mundo\n"
        "/playlist crear motivacion\n"
        "/playlist add motivacion | believer imagine dragons"
    )
